before_script:
  - 'sh -e /etc/init.d/xvfb start'
  - 'export DISPLAY=:99.0'
bundler_args: --without development production --quiet
env:
  - GEM='api:sqlite'
  - GEM='api:mysql'
  - GEM='api:postgres'
  - GEM='core:sqlite'
  - GEM='core:mysql'
  - GEM='core:postgres'
  - GEM='dash:sqlite'
  - GEM='dash:mysql'
  - GEM='dash:postgres'
  - GEM='promo:sqlite'
  - GEM='promo:mysql'
  - GEM='promo:postgres'
script:
  - 'ci/travis.sh'
notifications:
  email:
    - ryan@spreecommerce.com
  irc:
    use_notice: true
    skip_join: true
    channels:
      - "irc.freenode.org#spree"
rvm:
  - 1.9.3
